### ISSUE TITLE
Override cypress config

### ISSUE THREAD

**Issue by PrimaMateria** [piopi/cypress-desktop#4]
I am trying to figure out how to override the `cypress.json` config file.
In the image, it is stored in `/src/`. 
Then, when I start the container, I only mount the `<PROJECT_ROOT>/cypress` to `/src/cypress`.
My project config file is not taken because it is stored in project root.
If I tried to mount project root into `/src`, then this will override the original content of `/src` with `entrypoint.sh` and container fails to start.

Wouldn't it make more sense to be able to mount the whole project root into `/src/project` and then start cypress from inside this folder? This way it would avoid clash with docker files - `entrypoint.sh`, but still allow seamless propagation of local config file.

**Comment by piopi** [comment]
Fixed in version `all-1.0.7` and `base:cypress9.1.1`
